# Generated by Django 4.0.2 on 2022-02-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first name', models.CharField(blank=True, max_length=150)),
                ('last name', models.CharField(blank=True, max_length=150)),
                ('email address', models.EmailField(blank=True, max_length=254)),
                ('turkish lira', models.FloatField(default=0)),
                ('usd', models.FloatField(default=0)),
                ('euro', models.FloatField(default=0)),
                ('bitcoin', models.FloatField(default=0)),
                ('etheruim', models.FloatField(default=0)),
                ('Total Balance', models.FloatField(default=0)),
                ('Inversting Balance', models.FloatField(default=0)),
            ],
        ),
    ]
