# Generated by Django 4.0.2 on 2022-02-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_myuser_firstname_alter_myuser_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
