# Generated by Django 3.2.9 on 2022-02-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
