# Generated by Django 4.0.2 on 2022-02-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='Inversting Balance',
            new_name='btcBalance',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='Total Balance',
            new_name='ethBalance',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='bitcoin',
            new_name='euroBalance',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='first name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='etheruim',
            new_name='investingBalance',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='last name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='euro',
            new_name='totalBalance',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='turkish lira',
            new_name='trBalance',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='usd',
            new_name='usdBalance',
        ),
    ]
