# Generated by Django 3.2.9 on 2022-02-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=450)),
                ('school', models.TextField(max_length=20)),
                ('projects', models.TextField(null=True)),
            ],
        ),
    ]
